#!/bin/sh


# Where is the log file to write to?
LOGFILE="/var/log/tweet.log"
PROG_ROOT="/usr/local/bin/mtwitter/"
TEMP_DIRECTORY="/tmp"
STATUS_MESSAGE="Log test"




sudo find $BACKUPDIR -type d -mtime +7  | xargs rm -rfv;

# Use the Twitter modules to post the information
cd "$PROG_ROOT"
./tcli.sh -c statuses -s "$STATUS_MESSAGE" > "$TEMP_DIRECTORY"/tmpdir_maintenance.$$.tmp

# Status should have posted to Twitter. Parse the response to check that it has;
cat "$TEMP_DIRECTORY"/tmpdir_maintenance.$$.tmp | grep \ > /dev/null

if [ "$?" == "1" ]
then 

# An error occurred
echo "An error occurred posting to Twitter" >> "$LOGFILE"

fi

# Tidy up
rm -f "$TEMP_DIRECTORY"/tmpdir_maintenance.$$.tmp

# Exit the script
echo "Saying Goodbye!"
exit

